import { Factory } from './types';

export const INITIAL_APPROVED_FACTORIES: Factory[] = [
  {
    id: 'fac-101',
    ownerId: 'system-seed',
    ownerEmail: 'contact@niletextiles.com',
    name: 'شركة النيل للغزل والمنسوجات الحديثة',
    description: 'مصنع متكامل لإنتاج الأقمشة القطنية 100% المصرية، البوليستر، وتجهيز وتطريز الملابس الجاهزة والزي الموحد للمؤسسات والشركات الكبرى.',
    sectors: ['ملابس ومنسوجات'],
    city: 'المحلة الكبرى',
    industrialArea: 'المنطقة الصناعية بالمحلة',
    address: 'شارع المصانع الرئيسي، المحلة الكبرى، الغربية',
    lat: 30.9706,
    lng: 31.1669,
    salesOfficer: {
      name: 'أحمد محمود رضوان',
      email: 'sales@niletextiles.com',
      phone: '+20 100 123 4567',
      whatsapp: '+201001234567',
      notes: 'متاح للرد السريع على طلبات التوريد بالجملة من 9 صباحاً حتى 5 مساءً'
    },
    purchasingOfficer: {
      name: 'م. طارق عبد الرحمن',
      email: 'procurement@niletextiles.com',
      phone: '+20 101 987 6543',
      whatsapp: '+201019876543',
      notes: 'مسؤول عن شراء الخيوط الخام، الأصباغ الكيميائية، ومعدات الصباغة'
    },
    status: 'approved',
    rating: 4.8,
    reviewsCount: 19,
    aiAutoResponderEnabled: true,
    aiAutoResponderPrompt: 'أنت مسؤول مبيعات شركة النيل للنسيج. الحد الأدنى للطلب (MOQ) هو 500 قطعة. نوفر عينات خلال 3 أيام. أسعار التيشيرت تبدأ من 85 جنيه والتوريد خلال أسبوعين.',
    productsList: ['أقمشة قطن 100%', 'زي موحد (يونيفورم)', 'مفروشات فندقية', 'خيوط مغزولة عالية الجودة'],
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
    approvedAt: '2026-09-02T12:00:00Z',
    approvedBy: 'Admin',
    isLocationVerified: true,
    locationVerifiedAt: '2026-09-02T12:00:00Z',
    locationVerifiedBy: 'هيئة الرقابة الصناعية',
    establishedYear: 1998,
    totalAreaM2: 18500,
    productionCapacity: '120 طن أقمشة شهرياً + 45,000 قطعة ملابس',
    productionLinesCount: 6,
    certifications: ['ISO 9001 (إدارة الجودة)', 'علامة CE الأوروبية', 'OEKO-TEX 100', 'سجل صناعي نشط'],
    exportMarkets: ['ألمانيا', 'إيطاليا', 'السعودية', 'الإمارات'],
    isExporter: true,
    commercialRegNo: '48291 / الغربية',
    workingDaysHours: 'السبت - الخميس: 8:00 ص - 5:00 م',
    website: 'https://niletextiles.example.com'
  },
  {
    id: 'fac-102',
    ownerId: 'system-seed',
    ownerEmail: 'info@pyramidspack.com',
    name: 'مجموعة الأهرام للكرتون ومواد التعبئة والتغليف',
    description: 'رائدون في تصنيع الكرتون المضلع، الكراتين ثلاثية وخماسية الطبقات، الأكياس الورقية الصديقة للبيئة والعلب الدوائية والغذائية الفاخرة.',
    sectors: ['ورق وطباعة وتغليف'],
    city: 'العاشر من رمضان',
    industrialArea: 'المنطقة الصناعية الثالثة B3',
    address: 'القطعة 44، المنطقة الصناعية B3، العاشر من رمضان',
    lat: 30.3012,
    lng: 31.7415,
    salesOfficer: {
      name: 'سارة خالد المنياوي',
      email: 'sara.sales@pyramidspack.com',
      phone: '+20 102 334 4556',
      whatsapp: '+201023344556',
      notes: 'عروض تسعير فورية للطلبات التي تتعدى 10,000 كرتونة مع إمكانية الطباعة فلكسو وأوفست'
    },
    purchasingOfficer: {
      name: 'م. إبراهيم فؤاد',
      email: 'supply@pyramidspack.com',
      phone: '+20 109 887 7665',
      whatsapp: '+201098877665',
      notes: 'استقبال عروض رولات الورق كرافت واللواصق الصناعية والأحبار المائية'
    },
    status: 'approved',
    rating: 4.9,
    reviewsCount: 32,
    aiAutoResponderEnabled: true,
    aiAutoResponderPrompt: 'أنت مسؤول مبيعات الأهرام للكرتون والتغليف. نقدم كرتون مضلع بسماكات C/B/E مع طباعة مخصصة حتى 6 ألوان. الحد الأدنى للكرتون المخصص هو 2000 قطعة.',
    productsList: ['كرتون مضلع 3 و5 طبقات', 'أكياس ورقية بمقابض', 'علب دواء معتمدة', 'فواصل كرتونية لحماية المنتجات'],
    createdAt: '2026-09-03T11:30:00Z',
    updatedAt: '2026-09-03T11:30:00Z',
    approvedAt: '2026-09-04T09:15:00Z',
    approvedBy: 'Admin',
    isLocationVerified: true,
    locationVerifiedAt: '2026-09-04T09:15:00Z',
    locationVerifiedBy: 'جهاز العاشر من رمضان الصناعي',
    establishedYear: 2008,
    totalAreaM2: 12400,
    productionCapacity: '1,800,000 كرتونة مضلعة شهرياً',
    productionLinesCount: 4,
    certifications: ['ISO 9001 (إدارة الجودة)', 'ISO 14001 (البيئة)', 'اعتماد سلامة الغذاء (NFSA)', 'سجل صناعي نشط'],
    exportMarkets: ['الأردن', 'العراق', 'ليبيا', 'السعودية'],
    isExporter: true,
    commercialRegNo: '109842 / الشرقية',
    workingDaysHours: 'السبت - الخميس: 8:30 ص - 5:30 م',
    website: 'https://pyramidspack.example.com'
  },
  {
    id: 'fac-103',
    ownerId: 'system-seed',
    ownerEmail: 'contact@deltasteel.com',
    name: 'الدلتا للصناعات الهندسية والحديد والصلب',
    description: 'تشكيل وقص المعادن بالليزر CNC، تصنيع الجمالونات والهياكل المعدنية للمصانع، درابزينات، قطاعات حديدية، وأبواب الحريق المعتمدة.',
    sectors: ['صناعات هندسية ومعدنية', 'حديد وصلب ومعادن'],
    city: 'السادس من أكتوبر',
    industrialArea: 'المنطقة الصناعية الرابعة',
    address: 'مجمع الصناعات الثقيلة، محور 26 يوليو الصناعي، 6 أكتوبر',
    lat: 29.9723,
    lng: 30.9328,
    salesOfficer: {
      name: 'م. عمر الشريف',
      email: 'eng.omar@deltasteel.com',
      phone: '+20 111 223 3445',
      whatsapp: '+201112233445',
      notes: 'تنسيق المعاينات الهندسية ومقايسات الهناجر ومشاريع المقاولات الكبرى'
    },
    purchasingOfficer: {
      name: 'حازم السيد بدوي',
      email: 'procurement@deltasteel.com',
      phone: '+20 115 554 4332',
      whatsapp: '+201155544332',
      notes: 'شراء ألواح الصاج الأسود والمجلفن، غازات اللحام، وقطع غيار ماكينات الليزر'
    },
    status: 'approved',
    rating: 4.7,
    reviewsCount: 14,
    aiAutoResponderEnabled: true,
    aiAutoResponderPrompt: 'أنت مسؤول مبيعات الدلتا للحديد والصلب. نقوم بقص الصاج بالليزر بسماكة حتى 25 ملم وتصنيع الهناجر ومستودعات التخزين. نطلب تفاصيل المخطط الهندسي لتسعير دقيق.',
    productsList: ['قص ليزر وثني صاج', 'جمالونات وهياكل معدنية', 'أبواب مقاومة للحريق', 'مداخن صناعية وخزانات'],
    createdAt: '2026-09-05T08:00:00Z',
    updatedAt: '2026-09-05T08:00:00Z',
    approvedAt: '2026-09-05T14:20:00Z',
    approvedBy: 'Admin',
    isLocationVerified: true,
    locationVerifiedAt: '2026-09-05T14:20:00Z',
    locationVerifiedBy: 'هيئة التنمية الصناعية (IDA)',
    establishedYear: 2012,
    totalAreaM2: 24000,
    productionCapacity: '850 طن هياكل صلب ومعدات شهرياً',
    productionLinesCount: 5,
    certifications: ['ISO 9001 (إدارة الجودة)', 'ISO 45001 (السلامة والصحة المهنية)', 'علامة CE الأوروبية', 'اعتماد الدفاع المدني المصري للأبواب'],
    exportMarkets: ['السودان', 'تشاد', 'الكويت', 'عمان'],
    isExporter: true,
    commercialRegNo: '75319 / الجيزة',
    workingDaysHours: 'السبت - الأربعاء: 8:00 ص - 4:30 م',
    website: 'https://deltasteel.example.com'
  },
  {
    id: 'fac-104',
    ownerId: 'system-seed',
    ownerEmail: 'orders@greenfoodcorp.com',
    name: 'مزارع الواحة للصناعات الغذائية والتجميد',
    description: 'محطة تعبئة وتجميد وتصدير الخضروات والفواكه، صلصة الطماطم، والعصائر الطبيعية الحاصلة على شهادات الجودة العالمية ISO وBRC وHALAL.',
    sectors: ['صناعات غذائية ومشروبات'],
    city: 'مدينة بدر',
    industrialArea: 'منطقة الصناعات الغذائية',
    address: 'طريق مصر السويس الصحراوي، مدينة بدر الصناعية',
    lat: 30.1418,
    lng: 31.7161,
    salesOfficer: {
      name: 'ياسمين مصطفى',
      email: 'yasmine.m@greenfoodcorp.com',
      phone: '+20 122 889 9001',
      whatsapp: '+201228899001',
      notes: 'جاهزون لتوريد عقود التصدير للخليج وأوروبا، وحاويات التبريد'
    },
    purchasingOfficer: {
      name: 'م. شادي عز الدين',
      email: 'purchase@greenfoodcorp.com',
      phone: '+20 120 776 6554',
      whatsapp: '+201207766554',
      notes: 'عقود توريد المحاصيل الزراعية المباشرة من المزارع وأكياس البولي إيثيلين الغذائية'
    },
    status: 'approved',
    rating: 4.9,
    reviewsCount: 45,
    aiAutoResponderEnabled: true,
    aiAutoResponderPrompt: 'أنت مسؤول مبيعات مزارع الواحة للصناعات الغذائية. نوفر فراولة مجمدة IQF، بامية ممتازة، ومركزات عصائر. الحد الأدنى للتصدير هو حاوية 40 قدم مع شحن مبرد خلال 7 أيام.',
    productsList: ['فراولة مجمدة IQF', 'خضروات مشكلة معبأة', 'صلصة طماطم مركزة', 'عصائر مانجو وبرتقال طبيعي'],
    createdAt: '2026-09-06T10:00:00Z',
    updatedAt: '2026-09-06T10:00:00Z',
    approvedAt: '2026-09-07T11:00:00Z',
    approvedBy: 'Admin',
    isLocationVerified: true,
    locationVerifiedAt: '2026-09-07T11:00:00Z',
    locationVerifiedBy: 'الهيئة القومية لسلامة الغذاء',
    establishedYear: 2015,
    totalAreaM2: 31000,
    productionCapacity: '3,500 طن خضروات وفواكه مجمدة سنوياً',
    productionLinesCount: 8,
    certifications: ['ISO 22000 (سلامة الغذاء)', 'شهادة حلال (Halal)', 'BRC Global Standard', 'اعتماد سلامة الغذاء (NFSA)'],
    exportMarkets: ['الإمارات', 'السعودية', 'إنجلترا', 'روسيا', 'هولندا'],
    isExporter: true,
    commercialRegNo: '99214 / القاهرة',
    workingDaysHours: 'طوال الأسبوع (24/7 للمخازن المبردة)',
    website: 'https://greenfoodcorp.example.com'
  },
  {
    id: 'fac-105',
    ownerId: 'system-seed',
    ownerEmail: 'sales@chemcoplast.com',
    name: 'كيمكو للمبلمرات والصناعات البلاستيكية',
    description: 'إنتاج حبيبات البلاستيك البكر والمعاد تدويره، براميل وخزانات البولي إيثيلين عالية الكثافة HDPE، وأنابيب الري الحديث والتنقيط الزراعي.',
    sectors: ['بلاستيك ومطاط', 'صناعات كيميائية وأسمدة'],
    city: 'السادات',
    industrialArea: 'المنطقة الصناعية السادسة',
    address: 'المنطقة الصناعية 6، مدينة السادات، المنوفية',
    lat: 30.3758,
    lng: 30.5187,
    salesOfficer: {
      name: 'كريم البنداري',
      email: 'karim@chemcoplast.com',
      phone: '+20 106 554 3321',
      whatsapp: '+201065543321',
      notes: 'خصومات للكميات أكثر من 20 طن من خامات الـ Masterbatch والبولي بروبلين'
    },
    purchasingOfficer: {
      name: 'د. نبيل فكري',
      email: 'rnd@chemcoplast.com',
      phone: '+20 100 887 6654',
      whatsapp: '+201008876654',
      notes: 'شراء الإضافات الكيميائية، ومثبتات الأشعة فوق البنفسجية UV Stabilizers'
    },
    status: 'approved',
    rating: 4.6,
    reviewsCount: 11,
    aiAutoResponderEnabled: true,
    aiAutoResponderPrompt: 'أنت مسؤول مبيعات كيمكو للبلاستيك. نقدم مواسير الري بالتنقيط قطر 16 مم وخرطوم GR بضمان 5 سنوات. نوفر شحن لجميع المحافظات.',
    productsList: ['خراطيم ري بالتنقيط GR', 'براميل بلاستيك كيميائية 220 لتر', 'حبيبات بولي إيثيلين معاد تدويرها', 'صناديق خضار وفاكهة متينة'],
    createdAt: '2026-09-08T09:00:00Z',
    updatedAt: '2026-09-08T09:00:00Z',
    approvedAt: '2026-09-09T13:00:00Z',
    approvedBy: 'Admin',
    isLocationVerified: true,
    locationVerifiedAt: '2026-09-09T13:00:00Z',
    locationVerifiedBy: 'هيئة التنمية الصناعية - فرع السادات',
    establishedYear: 2017,
    totalAreaM2: 15800,
    productionCapacity: '600 طن منتجات بلاستيكية شهرياً',
    productionLinesCount: 5,
    certifications: ['ISO 9001 (إدارة الجودة)', 'ISO 14001 (البيئة)', 'سجل صناعي نشط'],
    exportMarkets: ['ليبيا', 'تونس', 'السودان'],
    isExporter: true,
    commercialRegNo: '33418 / المنوفية',
    workingDaysHours: 'السبت - الخميس: 8:00 ص - 5:00 م',
    website: 'https://chemcoplast.example.com'
  },
  {
    id: 'fac-106',
    ownerId: 'system-seed',
    ownerEmail: 'pharma@medialex.com',
    name: 'ميديالكس للصناعات الدوائية والمستلزمات الطبية',
    description: 'تصنيع السرنجات الطبية المعقمة، الكانيولات، محاليل الغسيل الكلوي، وعبوات الأدوية الزجاجية والبلاستيكية المطابقة لدستور الأدوية الأوروبي.',
    sectors: ['صناعات دوائية ومستحضرات تجميل'],
    city: 'برج العرب الجديدة',
    industrialArea: 'المنطقة الصناعية الثانية (منطقة الدواء)',
    address: 'بلوك 19، المنطقة الصناعية الثانية، برج العرب الجديدة، الإسكندرية',
    lat: 30.9124,
    lng: 29.5841,
    salesOfficer: {
      name: 'د. مروة الشاذلي',
      email: 'marwa.pharma@medialex.com',
      phone: '+20 128 334 9911',
      whatsapp: '+201283349911',
      notes: 'عقود مناقصات المستشفيات الحكومية والخاصة وهيئة الشراء الموحد'
    },
    purchasingOfficer: {
      name: 'د. أمجد سليم',
      email: 'qa@medialex.com',
      phone: '+20 127 665 4433',
      whatsapp: '+201276654433',
      notes: 'استيراد المواد الخام الطبية المعتمدة USP/EP وفلاتر التعقيم الطبي'
    },
    status: 'approved',
    rating: 4.9,
    reviewsCount: 28,
    aiAutoResponderEnabled: true,
    aiAutoResponderPrompt: 'أنت مسؤول مبيعات ميديالكس الدوائية. منتجاتنا معقمة بغاز ETO وحاصلة على CE Mark وشهادة هيئة الدواء المصرية EDA. التوريد فوري للكميات الكبيرة.',
    productsList: ['سرنجات معقمة 3 مل و5 مل', 'كانيولات وريدية مقاسات مختلفة', 'جوانتيات طبية لاتكس ونيتريل', 'أمبولات زجاجية دوائية'],
    createdAt: '2026-09-10T12:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
    approvedAt: '2026-09-11T16:00:00Z',
    approvedBy: 'Admin',
    isLocationVerified: true,
    locationVerifiedAt: '2026-09-11T16:00:00Z',
    locationVerifiedBy: 'هيئة الدواء المصرية (EDA)',
    establishedYear: 2014,
    totalAreaM2: 21000,
    productionCapacity: '12,000,000 قطعة مستلزمات طبية معقمة شهرياً',
    productionLinesCount: 7,
    certifications: ['ISO 13485 (الأجهزة الطبية)', 'علامة CE الأوروبية', 'اعتماد هيئة الدواء المصرية (EDA)', 'GMP المعتمد'],
    exportMarkets: ['المملكة العربية السعودية', 'الأردن', 'كينيا', 'نيجيريا'],
    isExporter: true,
    commercialRegNo: '65219 / الإسكندرية',
    workingDaysHours: 'طوال الأسبوع (مناوبة مستمرة)',
    website: 'https://medialex.example.com'
  }
];
